name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Go to repository files
        run: cd ${{ github.workspace }}
      - name: Echo file list into files.txt
        run: ls -lh > files.txt
      - name: Set up git
        run: git config user.name github-actions-test ; git config user.email videocreator+github-actions@outlook.de
      - name: Commit changes to files.txt
        run: git add files.txt ; git commit -m "Update files.txt" ; git push
      - run: echo "🍏 This job's status is ${{ job.status }}."
